# -- Main Menu --

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Join Us"
  pageRef = "join"
  weight = 20

[[main]]
  name = "Substack"
  url = "https://aiatunm.substack.com"
  weight = 30
